stages:
   - build
build_code:
  stage: build
  image: node:latest
  before_script:
    - npm install --silent
  script:
      - node_modules/.bin/ng build --prod --aot
  artifacts:
    name: "project-$CI_COMMIT_REF_NAME"
    paths:
      - dist/
      